services:
  - type: web
    name: drefootball-fcm
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

